# Generated by Django 6.0.5 on 2026-05-14 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook',
            field=models.FileField(blank=True, null=True, upload_to='ebooks/'),
        ),
    ]
